### ISSUE TITLE
Add localization program guideline for framework related i18n update

### ISSUE THREAD

**Issue by TonSquare** [TownSquareXYZ/ton-docs#66]
### Is your feature request related to a problem? Please describe.

Currently we don't have a guideline explaining how to add i18n for header/footer/sidebar, which is not supported by the crowdin translation.

### Describe the solution you'd like

We need add this part under `How To Contribute ->  Developers` section.

**Comment by sansx** [comment]
done 

https://ton-docs-git-i18nfeat-townsquarexyz.vercel.app/mandarin/contribute/localization-program/how-to-contribute#developer
