### ISSUE TITLE
Misused markdown header causing wrong display

### ISSUE THREAD

**Issue by infinityspectra** [TownSquareXYZ/ton-docs#67]
### Describe the bug

Check this screenshot: 

<img width="1238" alt="image" src="https://github.com/user-attachments/assets/de5b21e1-35e2-4972-ab66-c01cbc13bc5f">

Might caused by the misused header syntax:

https://github.com/TownSquareXYZ/ton-docs/blob/dc26e1a8f09dedf16fc4df470d3140a0fda1aeb2/docs/contribute/localization-program/how-it-works.md?plain=1#L18-L22

### To reproduce

Just check the previewed version.

### Expected behavior

`GitHub Synchronization for Documentation and Translations` should be the parent title of `Branches Overview`

**Comment by sansx** [comment]
🎉Thanks for the report on this issue, our newest version will be like this:

<img width="338" alt="image" src="https://github.com/user-attachments/assets/13721bbb-c4e3-4f62-b3e7-0a52629d17fc">
