### ISSUE TITLE
Mandarin docs footer i18n missing

### ISSUE THREAD

**Issue by TonSquare** [TownSquareXYZ/ton-docs#82]
### Is your feature request related to a problem? Please describe.

<img width="1307" alt="image" src="https://github.com/user-attachments/assets/067119d8-a1e5-4525-ac40-fa26f29356b3">

### Describe the solution you'd like

Update footer related i18n config.

Related to https://github.com/TownSquareXYZ/ton-docs/issues/66

**Comment by sansx** [comment]
the fix and newest guides are in #89, when it's ready we can update this to upstream :D

**Comment by sansx** [comment]
fixed here, preview:

https://ton-docs-git-i18nfeat-townsquarexyz.vercel.app/mandarin/contribute/localization-program/how-to-contribute#developer

<img width="1206" alt="image" src="https://github.com/user-attachments/assets/997b5112-5eda-4dfe-a1c3-58dadf6031bd">
